### ISSUE TITLE
 AttributeError: BatchTracer has no attribute split while running on Colab

### ISSUE THREAD

**Issue by erfanhamdi** [pkmtum/Semi-supervised_Invertible_Neural_Operators#3]
Hi Sebastian,

I am getting this error when I am trying to run the code for the antiderivative case on google colab.

regards,

**Comment by SebastianKaltenbach** [comment]
Dear Erfan,
thanks for reaching out.
Unfortunately some of the packages used in Colab have been updated since the code has been published.
For the antiderivative case, I updated the file and here is a link to a Google Colab which should run as of May 2024:
https://colab.research.google.com/drive/1t2eTwcTaWX5Jn92VR3ny4eIRBVFS2nqE?usp=sharing

Best,
Sebastian

**Comment by erfanhamdi** [comment]
thank you! now it is working
